export const HUD = {
  th: {
    shop: "ร้านค้า",
    items: "ไอเทม",
    bonuses: "โบนัสทีม",
    stats: "สถิติ",
    summary: "สรุปรอบ",
    guide: "คู่มือ",
    settings: "ตั้งค่า",
    players: "ผู้เล่น",
    traits: "สายสัมพันธ์",
    context: "ข้อมูลตัวละคร",
    own: "กลับสนามตัวเอง",
    view: "กำลังดูสนาม",
    bench: "ตัวสำรอง",
    round: "รอบ",
    gold: "ทอง",
    level: "เลเวล",
    connected: "เชื่อมต่อแล้ว",
    reconnect: "กำลังเชื่อมต่อใหม่",
    waiting: "กำลังรอข้อมูลจากเซิร์ฟเวอร์",
    itemChoice: "เลือกไอเทม 1 ชิ้น",
    augmentChoice: "เลือกโบนัสทีม",
    finished: "ผลการแข่งขัน",
    again: "เล่นอีกครั้ง",
    home: "กลับหน้าหลัก",
    result: "ผลการต่อสู้",
    income: "รายได้",
    events: "เหตุการณ์",
    empty: "ยังไม่มีข้อมูล",
    selected: "ได้รับรางวัลแล้ว",
    automatic: "หมดเวลา · เซิร์ฟเวอร์เลือกให้แล้ว",
    prep: "เตรียมทีม",
    battle: "ต่อสู้",
    choosing: "เลือกรางวัล",
    resolving: "ผลรอบ",
    lobby: "รอผู้เล่น",
    collapse: "ย่อ/ขยายแผง",
    inspect: "รายละเอียด",
    rotate: "แนวนอนมีพื้นที่จัดทีมมากขึ้น",
    auto: "AUTO · เติมช่องว่างเมื่อหมดเวลา",
    help: "เลือกตัวละครเพื่อดูสกิลและไอเทม",
    sound: "เสียง",
    motion: "ลดการเคลื่อนไหว",
    speed: "ความเร็วภาพต่อสู้",
    language: "ภาษา",
    xp: "ซื้อ 4 XP · 4 ทอง",
    new: "ใหม่",
  },
  en: {
    shop: "Shop",
    items: "Items",
    bonuses: "Bonuses",
    stats: "Stats",
    summary: "Round summary",
    guide: "Guide",
    settings: "Settings",
    players: "Players",
    traits: "Synergies",
    context: "Unit info",
    own: "Own board",
    view: "Viewing",
    bench: "Reserves",
    round: "Round",
    gold: "Gold",
    level: "Level",
    connected: "Connected",
    reconnect: "Reconnecting",
    waiting: "Waiting for server state",
    itemChoice: "Choose one item",
    augmentChoice: "Choose a team bonus",
    finished: "Match results",
    again: "Play again",
    home: "Home",
    result: "Battle result",
    income: "Income",
    events: "Events",
    empty: "No data yet",
    selected: "Reward received",
    automatic: "Time expired · server selected",
    prep: "Preparation",
    battle: "Battle",
    choosing: "Choose rewards",
    resolving: "Results",
    lobby: "Lobby",
    collapse: "Collapse / expand",
    inspect: "Details",
    rotate: "Landscape gives your formation more room",
    auto: "AUTO · fills empty slots at timeout",
    help: "Select a recruit to inspect skills and items",
    sound: "Sound",
    motion: "Reduced motion",
    speed: "Playback speed",
    language: "Language",
    xp: "Buy 4 XP · 4 gold",
    new: "New",
  },
};
