export type Locale = "th" | "en";
export const LABELS = {
  th: {
    scout: "ส่องทีมคู่แข่ง",
    own: "กลับสนามตัวเอง",
    watch: "กำลังดูสนามของ",
    ownStock: "ร้านค้าและตัวสำรองด้านล่างเป็นของคุณ",
    out: "ตกรอบแล้ว",
    offline: "ขาดการเชื่อมต่อ",
    next: "ขาดอีก",
    level: "ระดับ",
    tier: "ขั้น",
    practice: "โหมดฝึกเล่น",
    difficulty: "ความยาก",
    fair: "ผู้เล่น 1 คนและบอท 3 ตัว · บอทไม่มีโบนัสทรัพยากร",
    choices: "เลือกของรางวัล",
    item: "เลือกไอเทม 1 ชิ้น",
    augment: "เลือกโบนัสทีม 1 อย่าง",
    waiting: "เลือกแล้ว · รอผู้เล่นอื่นหรือหมดเวลา",
    timeout: "หมดเวลา ระบบเลือกตัวเลือกแรกที่ยังไม่ได้เลือก",
    recommend: "คำแนะนำเท่านั้น",
    rarity: "ระดับไอเทม",
    common: "ทั่วไป",
    rare: "พิเศษ",
    role: "เหมาะกับ",
    owned: "โบนัสทีมที่เลือกแล้ว",
    duration: "มีผลตลอดแมตช์ ไม่ซ้ำและไม่ทับซ้อนกลุ่มขัดแย้ง",
    income: "รายได้รอบล่าสุด",
    summary: "สรุปการต่อสู้",
    round: "รอบ",
    gold: "ทอง",
    total: "รวม",
    before: "ก่อนรับ",
    after: "หลังรับ",
    topDamage: "ทำความเสียหายสูงสุด",
    topTaken: "รับความเสียหายสูงสุด",
    casts: "ใช้สกิล",
    shields: "สร้างโล่",
    broken: "โล่แตก",
    survivors: "ยูนิตที่เหลือ",
    hpLoss: "เสียพลังชีวิตผู้เล่น",
    traits: "โบนัสเผ่าและสาย",
    enemy: "ฝ่ายตรงข้าม",
    log: "เหตุการณ์ต่อสู้",
    replace: "ต้องเพิ่มช่องหรือเปลี่ยนตัวบนสนามก่อน ผลจริงขึ้นกับตัวที่ถอด",
    duplicate: "ชนิดนี้อยู่บนสนามแล้ว จึงไม่นับเพิ่ม",
    activate: "เมื่อลงสนาม จะเปิดโบนัส",
    upgrade: "เมื่อลงสนาม จะเพิ่มขั้นโบนัส",
    progress: "เมื่อลงสนาม จะเข้าใกล้โบนัส",
    overflow: "ไอเทมรอเข้ากระเป๋า",
    empty: "ยังไม่มีข้อมูล",
    language: "ภาษาระบบกลยุทธ์",
    chosen: "เลือกแล้ว",
    pool: "ร้านค้าจองสำเนาจากกองร่วม · ช่องว่างอาจเกิดจากสำเนาหมด",
  },
  en: {
    scout: "Scout opponents",
    own: "Return to your board",
    watch: "Watching",
    ownStock: "The shop and bench below remain yours",
    out: "Eliminated",
    offline: "Disconnected",
    next: "Needed",
    level: "Level",
    tier: "Tier",
    practice: "Solo practice",
    difficulty: "Difficulty",
    fair: "1 player and 3 bots · no resource bonuses",
    choices: "Choose rewards",
    item: "Choose 1 item",
    augment: "Choose 1 team bonus",
    waiting: "Selected · waiting for others or timeout",
    timeout: "On timeout, the first remaining option is selected",
    recommend: "Suggestion only",
    rarity: "Item tier",
    common: "Common",
    rare: "Special",
    role: "Recommended role",
    owned: "Selected team bonuses",
    duration: "Lasts the match; no duplicates or conflicting tags",
    income: "Latest income",
    summary: "Battle summary",
    round: "Round",
    gold: "Gold",
    total: "Total",
    before: "Before",
    after: "After",
    topDamage: "Most damage dealt",
    topTaken: "Most damage taken",
    casts: "Skill casts",
    shields: "Shield granted",
    broken: "Shields broken",
    survivors: "Survivors",
    hpLoss: "Player HP lost",
    traits: "Traits",
    enemy: "Opponent",
    log: "Combat events",
    replace:
      "Requires capacity or replacing a deployed unit; results depend on the removed unit",
    duplicate: "Already deployed: duplicate definitions do not add traits",
    activate: "When deployed, activates",
    upgrade: "When deployed, upgrades",
    progress: "When deployed, progresses",
    overflow: "Items awaiting inventory space",
    empty: "No data yet",
    language: "Strategy language",
    chosen: "Selected",
    pool: "Offers reserve shared copies; empty slots can mean exhausted supply",
  },
} as const;
export const TRAIT_NAMES: Record<string, { th: string; en: string }> = {
  Emberkin: { th: "เผ่าอัคคี", en: "Emberkin" },
  Tideborn: { th: "เผ่าธารา", en: "Tideborn" },
  Verdant: { th: "เผ่าพฤกษา", en: "Verdant" },
  Astral: { th: "เผ่าดารา", en: "Astral" },
  Ironveil: { th: "เผ่าเหล็ก", en: "Ironveil" },
  Warden: { th: "ผู้พิทักษ์", en: "Warden" },
  Striker: { th: "นักจู่โจม", en: "Striker" },
  Ranger: { th: "นักยิง", en: "Ranger" },
  Arcanist: { th: "จอมเวท", en: "Arcanist" },
  Weaver: { th: "ผู้ประสาน", en: "Weaver" },
};
export const ROLE_NAMES: Record<string, { th: string; en: string }> = {
  Tank: { th: "แนวหน้า", en: "Tank" },
  Mage: { th: "จอมเวท", en: "Mage" },
  Ranger: { th: "นักยิง", en: "Ranger" },
};
export const ITEM_TEXT: Record<string, string> = {
  sunshard: "พลังโจมตี +22",
  heartglass: "พลังชีวิต +200",
  ironleaf: "เกราะ +25",
  mistcloak: "ต้านทานเวท +25",
  windcoil: "ความเร็วโจมตี +25%",
  moonwell: "มานาเริ่มต้น +30 และมานาต่อการโจมตี +5",
  bloodopal: "การโจมตีปกติฟื้นฟู 20% ของพลังชีวิตที่ทำให้ศัตรูเสีย",
  thornseal: "เมื่อถูกโจมตี สะท้อนความเสียหายเวท 16",
  dawnshell: "หนึ่งครั้งต่อการต่อสู้ เมื่อพลังชีวิตต่ำกว่า 30% ได้โล่ 300",
  stormpin: "ทุกการโจมตีครั้งที่สาม ทำความเสียหายเวทเพิ่ม 70",
  dewstone: "ฟื้นฟูพลังชีวิต 12 ต่อวินาที",
  prismfang: "โอกาสคริติคอล +20% การโจมตีคริติคอลทำความเสียหาย 150%",
};
export const INCOME_LABELS = {
  th: {
    base: "เงินพื้นฐาน",
    interest: "ดอกเบี้ย",
    win: "โบนัสชนะ",
    loss: "โบนัสแพ้",
    winStreak: "ชนะต่อเนื่อง",
    loseStreak: "แพ้ต่อเนื่อง",
    augment: "โบนัสทีม",
    other: "อื่น ๆ",
    capped: "หักส่วนเกินเพดาน",
  },
  en: {
    base: "Base",
    interest: "Interest",
    win: "Victory",
    loss: "Defeat",
    winStreak: "Win streak",
    loseStreak: "Loss streak",
    augment: "Team bonus",
    other: "Other",
    capped: "Capped",
  },
};
